#!/bin/sh

set -xe

(
  # Work around low default file descriptor limit (256) in OS X.
  # https://github.com/hashicorp/vagrant/issues/2435#issuecomment-73500032
  ulimit -n
  ulimit -n 512
  vagrant up
)
time vagrant ssh -- '
  set -e
  cd /vagrant/tests
  sudo PATH=/vagrant/bin:$PATH ./example-script.sh

  container_dir=/var/cookie-cutter/containers/my-container/
  expect_file () {
    file="$1"
    if ! [ -f "$file" ]; then
      echo "Missing file: $file" >&2
      exit 1
    fi
  }
  expect_file "$container_dir/test-passed"
  expect_file "$container_dir/srv/my-app/example-script.sh"
  echo "TESTS PASSED."
' || { echo "TESTS FAILED!" >&2; exit 1; }
