#!/bin/sh

set -e
cd "$(dirname $0)"

sudo PATH=/vagrant/bin:$PATH bash -c '
  . test-lib.sh

  run_all () {
    for test in "$@"; do
      # Strip "tests/" prefix.
      . "${test#"tests/"}"
    done
  }

  if [ -z "$1" ]; then
    run_all cases/*.sh
  else
    run_all "$@"
  fi

  summarize_tests
' "$0's bash -c" "$@"
